### ISSUE TITLE
Cannot build the project as is

### ISSUE THREAD

**Issue by CromFr** [kevL/FXE_Generator#1]
Hi o/

As is, the project fails to build because it requires NAudio source files, that are located at src/NAudio and not included in the repository (ignored by the .gitignore)

I was able to build the solution by removing the NAudio files from the project and adding the NAudio NuGET package to the project dependencies. I can submit a PR with these modifications if you want ;)

Also you should consider uploading binary releases in the github releases page, so people can easily download and use this fantastic tool !

**Comment by kevL** [comment]
heya Crom,
glad to hear a bit of interest in this ... :)

I took 0100010's [original author's] code to a better place yes. But i couldn't complete the stuff/extensions i was working on ... primarily the waveform display and using it to adjust values in the FXE-output. There seems to be M$ quirks and anomalies in their proprietary speech/recognition engine(s). iirc, one of their event-values wasn't resetting properly, or was resetting itself when i didn't want it to -- it drops the current position in the sound, at some point when it fails a recognition or I can't remember exactly.

The other issue I ran into was that the format(s) for FXE and FXE-related data is undocumented, i just couldn't find any. If you look through the code, there's some stuff that's extremely head-scratching. Eg. [Smoother.cs](https://github.com/kevL/FXE_Generator/blob/master/src/Smoother.cs)

re. NAudio
remarkable piece of work there! But vastly overcomplicated for the waveform viewer in the FXE Generator. So i studied it and then parsed out and simpified only the stuff that I needed (with credits to Mark Heath et al. - the NAudio libraries ofc). See [WaverF.cs #region handlers kL_audio](https://github.com/kevL/FXE_Generator/blob/b6bf16282995d5ef64d32da786567fd782468593/src/WaverF.cs#L508)

Ie, there should be no references to src/NAudio in the FXE Generator's code ... only to [src/kL_Audio](https://github.com/kevL/FXE_Generator/tree/master/src/kL_Audio)

So, not sure what's up there but I never did try to bring the code to a fully robust state.

if you Open and Generate data, the Edit... button enables. WARNING: i can't remember if I got the Editor to a working state, transfering its values back into the PHONEMES panel. Note this is a feature that 0100010 wanted but never got around to it. And at the bottom of the Editor is a ~ button ( ~ == the Waver display ) as you can see if you have a look it was getting so close ...

/at present i'm heavily engaged in updating a different project; eta unknown but any comments you can make on the Generator are noted and appreciated

**Comment by CromFr** [comment]
Thanks for your response :)

The csproj file references many NAudio files: https://github.com/kevL/FXE_Generator/blob/master/FXE_Generator.csproj#L84-L166
I just realised that I didn't need to setup the NAudio dependency to build the project, simply removing the non-existing NAudio files from the project is enough to build it

**Comment by kevL** [comment]
oh right. They're there simply to navigate through them in the IDE

/salut

**Comment by kevL** [comment]
https://github.com/kevL/FXE_Generator/commit/3908355df11106d7e7af0438e57c7b159b2dac86
